### PR TITLE
feat: line filter in search

### PR DESCRIPTION
**Pull request by mortennordseth**
This adds the functionality to filter lines in the travel search. 

image

Closes https://github.com/AtB-AS/kundevendt/issues/16679

### CODE REVIEW

**Comment by jonasbrunvoll** [comment]
The trip planner does not work quite as it should when the trip has first been specified and then removed. The trip search does not work Initially when specifying the line number, the search returns trips from the specified line. Example image 1, where line 800 is specified. Then, when removing the specified line, the search does not    

### Illustration
<details>
<Summary>screenshots/video</Summary>

Screenshot 2024-02-06 at 14 59 45

Screenshot 2024-02-06 at 14 59 54


</details>

**Comment by mortennordseth** [comment]
> The travel planner does not work quite as it should when the trip has first been specified and then removed.

> Example: When fist specifying the line 800, the travel planner returns trips from the line 800. Then, when removing the specified line 800, the search does not return any results.

Fixed :)

**Comment by jonasbrunvoll** [comment]
> > The travel planner does not work quite as it should when the trip has first been specified and then removed.
> 
> > Example: When fist specifying the line 800, the travel planner returns trips from the line 800. Then, when removing the specified line 800, the search does not return any results.
> 
> Fixed :)

Nice🙌

**Comment by jonasbrunvoll** [comment]
Another observation. When searching after trips from Ålesund to Molde, the result is empty both when line 100 and when line 905 is specified. When none line is specified, trips with both of these line numbers are returned. 


<details>
<Summary>screenshots/video</Summary>
Screenshot 2024-02-06 at 16 52 55
Screenshot 2024-02-06 at 16 53 11
Screenshot 2024-02-06 at 16 53 23
</details>

**Comment by mortennordseth** [comment]
This is because you are using AtBs version of the planner web while filtering for a FRAM bus. If you do the same search in FRAMs version, it would look like this: 

image

We need to add a message for empty results though

**Comment by jonasbrunvoll** [comment]
> This is because you are using AtBs version of the planner web while filtering for a FRAM bus. If you do the same search in FRAMs version, it would look like this:
> 
> image
> We need to add a message for empty results though

Ah, I see! Yes, adding a message for empty results would be helpful👍

**Review by jonasbrunvoll — APPROVED** [review]
Looks good🙌

**Comment by mikaelbr** [comment]
Think the tests here fails due to not merged changes from main 🤔

**Comment by mikaelbr** [comment]
I'll clean up and fix merge conflicts here

**Pull request merged**
