### PR TITLE
fix: general performance for travel planner

### PR DESCRIPTION
**Pull request by mikaelbr**
Improves performance by:

- Making more calls in parallell
- Removing unused data from trip planner query
- Increasing search window for trips.
- Fixing bug in do-while loop condition.

### CODE REVIEW

**Comment by adriansberg** [comment]
Did you do any measurements?

**Comment by mikaelbr** [comment]
No, but this in many cases removes 3 gql trip calls and parallels 2 calls, making it essentially going from 5 calls in sequence to 2 calls. So 2/5 of the original time.

**Review by mortennordseth — APPROVED** [review]
Nice! 👍 Some of the data that you've removed is needed for the trip details that I am currently working on. I can add what is needed or it might actually be better to create a new query that is used when getting a specific trip for trip details. Either way, I'll handle that in the PR for trip details

**Comment by mikaelbr** [comment]
I think it is better to have separate fetch points for details and list, as they have different requirements and require different data

**Pull request merged**
