### PR TITLE
fix: update selected color of search time selector

### PR DESCRIPTION
**Pull request by adriansberg**
Update selected color of search time selector.

image

image

### CODE REVIEW

**Review by mortennordseth — APPROVED** [review]
Looks better! 👍 Can we apply these changes to the widget as well, without creating a new release? We can look into fixing that tomorrow of course

**Comment by mikaelbr** [comment]
Yes, but the cache time would make the change slow for existing users. isn't a huge problem for now, but just makes it harder to verify. I can update the widget

**Comment by adriansberg** [comment]
I have applied the changes to the widget's css.

**Comment by mikaelbr** [comment]
oh yes, saw that now!

**Review by mikaelbr — APPROVED** [review]

**Pull request merged**
