### PR TITLE
feat: adds maximum interchange wait time to details page. Fixes #18410

### PR DESCRIPTION
**Pull request by mikaelbr**
Fixes https://github.com/AtB-AS/kundevendt/issues/18410

I'm unsure whether or not to actually handle the null case or just treat it as 0. But for now, if the max wait time is 0 we just treat it as not defined. 🤔 Open to actually handle it explicitly though.

Screenshot 2024-06-24 at 19 39 54

### CODE REVIEW

**Comment by adriansberg** [comment]
2024-06-24 at 23 05 50@2x

Shouldn't the wait time in theory be about 2 minutes in this case? Is the reason it is showing that the `maximumWaitTime` is greater than 0, but less than 1?

**Comment by mikaelbr** [comment]
If the time isn't shown it is defined as 0 in the API. Don't know if business logic says that 0 = 2, but can check with Christoffer.

**Comment by mikaelbr** [comment]
But seeing here waiting 0 minutes is not good 😬

**Comment by adriansberg** [comment]
> But seeing here waiting 0 minutes is not good 😬

That means it _is_ defined some how?

**Comment by mikaelbr** [comment]
Yeah, and non-zero.

**Comment by mikaelbr** [comment]
In FRAM at least the value will always be set and is Required by Hogia. So I think the best course of action is to hide it as intended for now. Will check why this is 0 but not caught by that check

**Comment by mikaelbr** [comment]
In meråker case the maximum wait time was -1.

**Comment by adriansberg** [comment]
Typical Meråker I tell you.

**Review by adriansberg — APPROVED** [review]
Looks good now 🎉

**Review by mortennordseth — APPROVED** [review]
🙌

**Pull request merged**
